# PostgreSQL DB Host and Credentials
user_psg: <USER_PSG>
password_psg: <PASSW_PSG>
host_psg: 127.0.0.1
port_psg: 5432
database_psg: postgres

# SQL DB Host and Credentials for heatmap color tables
user_sql: <USER_SQL>
password_sql: <PASSW_SQL>
host_sql: <heapmap host>
database_sql: heatmap