# PostgreSQL DB Host and Credentials
user_psg: USER
password_psg: PASS
host_psg: HOST
port_psg: 5432
database_psg: DB

# SQL DB Host and Credentials for heatmap color tables
user_sql: USER
password_sql: PASS
host_sql: HOST
database_sql: DB

# urls
user_info: /auth/realms/master/protocol/openid-connect/userinfo
device_url: /iot-directory/api/device.php?
servicemap_url: /superservicemap/api/v1/?
service_uri: http://www.disit.org/km4city/resource/iot/
model_url: /iot-directory/api/model.php?